[build]
  publish = "dist/"
  command = "yarn generate --modern"

[[plugins]]
  package = "@netlify/plugin-sitemap"
  [plugins.inputs]
    buildDir = "dist"

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"
