backend:
  name: git-gateway
  branch: master
# backend:
#   name: proxy
#   proxy_url: http://localhost:8081/api/v1
#   branch: master

site_url: "https://bopp-kogn.africa"
display_url: "https://bopp-kogn.africa"
logo_url: "https://bopp-kogn.africa/bopp-kogn-inline.svg"
media_folder: "static/images"
public_folder: "/images"
editor:
  preview: false

collections: # A list of collections the CMS should be able to edit
  - name: "about"
    label: "About"
    folder: "content/en/about"
    extension: "yml"
    format: "yml"
    slug: "about"
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - label: "Abstract"
        name: "abstract"
        widget: "list"
        required: false
        fields:
          - label: "Part"
            name: "part"
            widget: "markdown"
            required: false
      - label: "Translations"
        name: "translations"
        widget: "list"
        fields:
          - label: "Translation"
            name: "translation"
            widget: object
            required: false
            fields:
              - {label: "Language", name: "language", widget: "string"}
              - {label: "Value", name: "value", widget: "string"}
  - name: "artists"
    summary: "{{title}}"
    label: "Artists"
    folder: "content/en/artists"
    extension: "md"
    slug: "{{fields.slug}}"
    create: true
    fields:
      - {label: Title, name: title, widget: string, tagname: "h1"}
      - {label: Slug, name: slug, widget: string}
      - {label: Role, name: role, widget: string, required: false}
      - {label: From, name: from, widget: string, required: false}
      - {label: Bio, name: body, widget: markdown, required: false}
      - label: Links
        name: links
        widget: list
        required: false
        fields:
          - label: Title
            name: title
            widget: string
          - label: Link
            name: href
            widget: string
      - {label: Avatar, name: avatar, widget: image, required: false}
      - label: "Media"
        name: "media"
        widget: "list"
        fields:
          - label: Image
            name: image
            summary: '{{title}}'
            widget: object
            required: false
            fields:
              - {label: Title, name: title, widget: string, required: false}
              - {label: Image, name: src, widget: image}
              - label: Artists
                name: artists
                widget: list
                fields:
                  - {label: Artist, name: relation, widget: relation, collection: artists, value_field: slug, display_fields: ['title'], search_fields: ['title', 'slug', 'role'], required: false}
              - label: Credits
                name: credits
                widget: object
                required: false
                fields:
                  - label: Credit
                    name: credit
                    widget: list
                    fields:
                      - {label: Text, name: text, widget: string, required: false}
                      - {label: Instagram, name: instagram, widget: string, required: false}
                      - {label: Website, name: website, widget: string, required: false}
  - name: "events" # Used in routes, ie.: /admin/collections/:slug/edit
    summary: "{{title}} | {{type}}"
    label: "Event" # Used in the UI, ie.: "New Post"
    folder: "content/en/events"
    extension: "md"
    slug: "{{fields.slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Slug", name: "slug", widget: "string", tagname: "h1"}
      - {label: "Cover Image", name: "image", widget: "image", required: false, tagname: ""}
      - {label: "Type", name: "type", widget: "string", tagname: "h1", required: false}
      - {label: "Subtitle", name: "subtitle", widget: "string", tagname: "h1", required: false}
      - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mma", picker_utc: false}
      - label: "Venue"
        name: "venue"
        required: false
        widget: object
        fields:
          - {label: "Name", name: "name", widget: "string", tagname: "h1", required: false}
          - {label: "Link", name: "venueLink", widget: "string", tagname: "h1", required: false}
      - {label: "Address", name: "address", widget: "string", tagname: "h1", required: false}
      - {label: "Price", name: "price", widget: "string", tagname: "h1", required: false}
      - {label: "Instagram", name: "instagram", widget: "string", tagname: "h1", required: false}
      - {label: "Facebook", name: "facebook", widget: "string", tagname: "h1", required: false}
      - {label: "Residentadvisor", name: "residentadvisor", widget: "string", tagname: "h1", required: false}
      - {label: "Live Stream", name: "livestream", widget: "string", tagname: "h1", required: false}
      - {label: "Reservation", name: "reservation", widget: "string", tagname: "h1", required: false}
      - {label: "Description", name: "body", widget: "markdown", required: false}
      - {label: "Meta Description", name: "meta_description", widget: "text", required: false}
      - label: "Artists"
        name: "artists"
        widget: "list"
        fields:
          - label: Artist
            name: artist
            widget: object
            required: false
            fields:
              - {label: Artist, name: relation, widget: relation, collection: artists, value_field: slug, display_fields: ['title'], search_fields: ['title', 'slug', 'role'], required: false}
              - {label: Name, name: title, widget: string, required: false}
              - {label: Role, name: role, widget: string, required: false}
              - {label: From, name: from, widget: string, required: false}
              - {label: Link, name: link, widget: string, required: false}
              - {label: Avatar, name: avatar, widget: image, required: false}
      - label: "Media"
        name: "media"
        widget: "list"
        fields:
          - label: Image
            name: image
            summary: '{{title}}'
            widget: object
            required: false
            fields:
              - {label: Title, name: title, widget: string, required: false}
              - {label: Image, name: src, widget: image}
              - label: Artists
                name: artists
                widget: list
                fields:
                  - {label: Artist, name: relation, widget: relation, collection: artists, value_field: slug, display_fields: ['title'], search_fields: ['title', 'slug', 'role'], required: false}
              - label: Credits
                name: credits
                widget: object
                required: false
                fields:
                  - label: Credit
                    name: credit
                    widget: list
                    fields:
                      - {label: Text, name: text, widget: string, required: false}
                      - {label: Instagram, name: instagram, widget: string, required: false}
